config/routes.rb
Rails.application.routes.draw do

  resources :questions

  resources :advertisements

  resources :topics do
    resources :posts, except: [:index]
    resources :sponsored_posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  post 'users/confirm' => 'users#confirm'

  get 'about' => 'welcome#about'

  get 'contact' => 'welcome#contact'

  get 'faq' => 'welcome#faq'

  root 'welcome#index'
end

app/models/sponsored_post.rb
class SponsoredPost < ActiveRecord::Base
  belongs_to :topic
end

app/controllers/sponsored_posts_controller.rb
class SponsoredPostsController < ApplicationController
  def show
    @sponsored_post = SponsoredPost.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @sponsored_post = SponsoredPost.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @sponsored_post = SponsoredPost.new
    @sponsored_post.title = params[:sponsored_post][:title]
    @sponsored_post.body = params[:sponsored_post][:body]
    @sponsored_post.price = params[:sponsored_post][:price]
    @sponsored_post.topic = @topic

    if @sponsored_post.save
      flash[:notice] = "Sponsored post was saved."
      redirect_to [@topic, @sponsored_post]
    else
      flash.now[:alert] = "There was an error saving the sponsored post. Please try again."
      render :new
    end
  end

  def edit
    @sponsored_post = SponsoredPost.find(params[:id])
  end

  def update
    @sponsored_post = SponsoredPost.find(params[:id])
    @sponsored_post.title = params[:sponsored_post][:title]
    @sponsored_post.body = params[:sponsored_post][:body]
    @sponsored_post.price = params[:sponsored_post][:price]

    if @sponsored_post.save
      flash[:notice] = "The sponsored post has been successfully updated."
      redirect_to [@sponsored_post.topic, @sponsored_post]
    else
      flash.now[:alert] = "There was an error with saving your changes. Please try again."
      render :edit
    end
  end

  def destroy
    @sponsored_post = SponsoredPost.find(params[:id])

    if @sponsored_post.destroy
      flash[:notice] = "\"#{@sponsored_post.title}\" was deleted successfully."
      redirect_to @sponsored_post.topic
    else
      flash.now[:alert] = "There was an error with deleting the sponsored post. Please try again."
      render :show
    end
  end
end

app/helpers/sponsored_posts_helper.rb
module SponsoredPostsHelper
end

app/views/sponsored_posts/_sponsored_post.html.erb
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to "#{sponsored_post.title} - $#{sponsored_post.price}.00", topic_sponsored_post_path(@topic, sponsored_post) %>
    </h4>
    <small>
      submitted <%= time_ago_in_words(sponsored_post.created_at) %> ago
    </small>
  </div>
</div>

app/views/sponsored_posts/edit.html.erb
<h1>Edit Sponsored Post</h1>

<div class="col-md-8">
  <%= form_for [@sponsored_post.topic, @sponsored_post] do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: 'Enter sponsored post title' %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: 'Enter sponsored post body' %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
  <% end %>
</div>

app/views/sponsored_posts/new.html.erb
<h1>New Sponsored Post</h1>

<div class="row">
  <div class="col-md-8">
    <%= form_for [@topic, @sponsored_post] do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: 'Enter sponsored post title' %>
      </div>
      <div class="form-group">
        <%= f.label :price %>
        <%= f.number_field :price %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: 'Enter sponsored post body' %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/sponsored_posts/show.html.erb
<h1><%= "#{@sponsored_post.title} - $#{@sponsored_post.price}" %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= @sponsored_post.body %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_topic_sponsored_post_path(@sponsored_post.topic, @sponsored_post), class: 'btn btn-success' %>
    <%= link_to "Delete Sponsored Post", [@sponsored_post.topic, @sponsored_post], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this sponsored post?'} %>
  </div>
</div>